/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.quantum.meditation;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int ic_launcher_background=0x7f050000;
    }
    public static final class drawable {
        public static final int ic_launcher_foreground=0x7f020000;
    }
    public static final class id {
        public static final int compose_view=0x7f080000;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int coherence=0x7f060004;
        public static final int create_freq=0x7f060002;
        public static final int ground_freq=0x7f060001;
        public static final int unity_freq=0x7f060003;
    }
    public static final class style {
        public static final int Theme_Material3_Dark=0x7f070000;
        public static final int Theme_QuantumMeditation=0x7f070001;
    }
}
