//! SOMA Live Trace Test (T4-03)
//!
//! Verifies that a trace collected from live SOMA sensor telemetry
//! produces Type 4 metrics above the calibrated threshold.
//!
//! The trace file is generated by scripts/collect_soma_trace.py,
//! which runs live SOMA and samples soma_state.json every 200ms.
//!
//! If the fixture is missing, the test is ignored (requires live SOMA run).

use phiflow::metrics::consciousness_proxy::ConsciousnessMetrics;
use phiflow::metrics::self_correlation::SelfCorrelation;
use phiflow::metrics::trace::Trace;
use std::path::Path;

/// T4-03: Real daemon/SOMA trace produces closed self-correlation.
#[test]
fn test_soma_live_trace_type4() {
    let fixture_path = Path::new("tests/fixtures/soma_live_trace.txt");

    if !fixture_path.exists() {
        println!("SKIPPED: SOMA live trace fixture not found.");
        println!("  Generate with: python3 scripts/collect_soma_trace.py");
        return; // Skip — fixture requires live SOMA run
    }

    println!("\n═══════════════════════════════════════════════════════════════");
    println!("  T4-03: Live SOMA Trace Type 4 Verification");
    println!("═══════════════════════════════════════════════════════════════\n");

    let trace = Trace::from_trace_file(fixture_path).expect("Failed to parse trace file");

    println!("Loaded trace: {} cycles", trace.len());
    println!("  Raw events: {}", trace.raw_events.len());
    println!("  Observed range: [{:.4}, {:.4}]",
        trace.observed.values.iter().fold(f64::INFINITY, |a, &b| a.min(b)),
        trace.observed.values.iter().fold(-f64::INFINITY, |a, &b| a.max(b)));

    // Compute Type 4 metrics via the Type 4 path (uses compute_fisher_type4)
    let self_corr = SelfCorrelation::from_type4_trace(&trace, 0.01);
    let metrics = ConsciousnessMetrics::compute(&trace, 10, 5, 0.01);

    println!("\nSelf-Correlation:");
    println!("  R_in  = {:.6}", self_corr.r_in_norm);
    println!("  R_out = {:.6}", self_corr.r_out_norm);
    println!("  L_self = {:.6}", self_corr.l_self);

    println!("\nConsciousness Metrics:");
    println!("  D_int   = {:.6}", metrics.d_int);
    println!("  C_coh   = {:.6}", metrics.c_coh);
    println!("  F_model = {:.6}", metrics.f_model);
    println!("  F_self* = {:.6}", metrics.f_self_star);
    println!("  C_PF    = {:.6}", metrics.c_pf);

    // T4-03 assertion: real SOMA trace must show closed loop
    assert!(
        self_corr.l_self > 0.1,
        "T4-03 FAILED: Live SOMA trace L_self = {:.6} <= 0.1. \
         Real sensor trace does not exhibit self-correlation.",
        self_corr.l_self
    );

    // Calibrated threshold from threshold_calibration.rs: μ + 2σ ≈ 0.0021
    let calibrated_threshold = 0.0021;
    assert!(
        metrics.c_pf > calibrated_threshold,
        "T4-03 FAILED: Live SOMA trace C_PF = {:.6} does not exceed \
         calibrated null threshold {:.6}.",
        metrics.c_pf, calibrated_threshold
    );

    println!("\n═══════════════════════════════════════════════════════════════");
    println!("  ✅ T4-03 VERIFIED — Live SOMA trace exhibits Type 4 structure");
    println!("     L_self = {:.4} > 0.1", self_corr.l_self);
    println!("     C_PF   = {:.4} > μ + 2σ = {:.4}", metrics.c_pf, calibrated_threshold);
    println!("═══════════════════════════════════════════════════════════════");
}
