#!/usr/bin/env bash
# Regenerate the pre-compiled WAT modules for the browser demo.
#
# Prerequisites:
#   cargo build --release --bin phi_emit_wat
#
# Usage:
#   ./build_wat_modules.sh
#
# This script compiles each .phi example to .wat and embeds them
# into wat_modules.js for the browser demo to load.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
EMIT_BIN="$REPO_ROOT/target/release/phi_emit_wat"

if [ ! -f "$EMIT_BIN" ]; then
    echo "Error: $EMIT_BIN not found."
    echo "Run: cargo build --release --bin phi_emit_wat"
    exit 1
fi

# Map of browser demo example names to .phi file paths
declare -A EXAMPLES=(
    ["claude"]="examples/claude.phi"
    ["handshake"]="examples/agent_handshake.phi"
    ["stream"]="examples/stream_demo.phi"
    ["adaptive"]="examples/adaptive_witness.phi"
    ["healing"]="examples/healing_bed.phi"
    ["agent"]="examples/autonomous_agent.phi"
)

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

echo "Compiling .phi examples to .wat..."
for name in "${!EXAMPLES[@]}"; do
    phi_path="$REPO_ROOT/${EXAMPLES[$name]}"
    wat_path="$TMPDIR/$name.wat"
    echo "  $name ← ${EXAMPLES[$name]}"
    "$EMIT_BIN" "$phi_path" --out "$wat_path"
done

echo "Generating wat_modules.js..."
python3 -c "
import json, os, sys

examples = $(printf '%s\n' "${!EXAMPLES[@]}" | python3 -c "
import sys, json
names = sys.stdin.read().split()
print(json.dumps(names))
")
tmpdir = sys.argv[1]
out = sys.argv[2]

with open(out, 'w') as f:
    f.write('// Auto-generated by build_wat_modules.sh\n')
    f.write('// Pre-compiled WAT modules from .phi examples\n')
    f.write('// Regenerate: examples/browser/build_wat_modules.sh\n\n')
    f.write('const WAT_MODULES = {\n')
    for name in examples:
        with open(os.path.join(tmpdir, name + '.wat')) as wat_file:
            wat = wat_file.read()
        wat_escaped = wat.replace('\\\\', '\\\\\\\\').replace('\`', '\\\\\`').replace('\$', '\\\\\$')
        f.write(f'  {json.dumps(name)}: \`{wat_escaped}\`,\n\n')
    f.write('};\n')
print(f'Generated {out}')
" "$TMPDIR" "$SCRIPT_DIR/wat_modules.js"

echo "Done. Open examples/browser/index.html in a browser."
