// Auto-generated by PhiFlow browser demo build script
// Pre-compiled WAT modules from .phi examples
// Generated by: cargo run --release --bin phi_emit_wat -- examples/X.phi --out /tmp/X.wat

const WAT_MODULES = {
  "claude": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$r22 f64)
    (local \$r23 f64)
    (local \$r24 f64)
    (local \$r25 f64)
    (local \$r26 f64)
    (local \$r27 f64)
    (local \$result f64)
    ;; Block 0
    ;; intention "LAMBDA_convergence" (name len fallback)
    i32.const 18
    call \$phi_intention_push
    f64.const 2
    local.set \$r23
    local.get \$r23
    local.set \$result
    nop ;; StoreVar \$r23
    local.get \$r23
    local.set \$r24
    local.get \$r24
    local.set \$result
    f64.const 0.6180339887498949
    local.set \$r25
    local.get \$r25
    local.set \$result
    nop ;; StoreVar \$r25
    i32.const -1
    call \$phi_witness
    local.set \$r26
    local.get \$r26
    local.set \$result
    local.get \$r25
    local.set \$r27
    local.get \$r27
    local.set \$result
    local.get \$r27
    call \$phi_resonate
    call \$phi_intention_pop
    ;; Return r0 unresolved — preserve last computed \$result
    local.get \$result
  )
)
`,

  "handshake": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$result f64)
    ;; Block 0
    ;; intention "announcing_to_field" (name len fallback)
    i32.const 19
    call \$phi_intention_push
    ;; intention "self_verification" (name len fallback)
    i32.const 17
    call \$phi_intention_push
    call \$phi_coherence
    local.set \$r12
    local.get \$r12
    local.set \$result
    nop ;; StoreVar \$r12
    local.get \$r12
    local.set \$r13
    local.get \$r13
    local.set \$result
    local.get \$r13
    call \$phi_resonate
    f64.const 0.6180339887498949
    local.set \$r14
    local.get \$r14
    local.set \$result
    nop ;; StoreVar \$r14
    local.get \$r14
    local.set \$r15
    local.get \$r15
    local.set \$result
    local.get \$r15
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r16
    local.get \$r16
    local.set \$result
    f64.const 0.1
    local.set \$r17
    local.get \$r17
    local.set \$result
    nop ;; StoreVar \$r17
    local.get \$r17
    local.set \$r18
    local.get \$r18
    local.set \$result
    local.get \$r18
    call \$phi_resonate
    call \$phi_intention_pop
    call \$phi_coherence
    local.set \$r19
    local.get \$r19
    local.set \$result
    nop ;; StoreVar \$r19
    local.get \$r19
    local.set \$r20
    local.get \$r20
    local.set \$result
    local.get \$r20
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r21
    local.get \$r21
    local.set \$result
    call \$phi_intention_pop
    local.get \$r21
    local.set \$result
    local.get \$result
  )
)
`,

  "stream": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 3
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    ;; Block 1
    ;; Block 2
    local.get \$r4
    local.set \$r2
    local.get \$r2
    local.set \$result
    f64.const 1
    local.set \$r3
    local.get \$r3
    local.set \$result
    local.get \$r2
        local.get \$r3
    f64.add
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    call \$phi_coherence
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    local.get \$r4
    local.set \$r6
    local.get \$r6
    local.set \$result
    local.get \$r6
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r7
    local.get \$r7
    local.set \$result
    local.get \$r4
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r1
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r8
        local.get \$r9
    f64.ge
    f64.convert_i32_s
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$result
  )
)
`,

  "adaptive": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0.62
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 0
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    ;; Block 1
    ;; Block 2
    local.get \$r4
    local.set \$r2
    local.get \$r2
    local.set \$result
    f64.const 1
    local.set \$r3
    local.get \$r3
    local.set \$result
    local.get \$r2
        local.get \$r3
    f64.add
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    call \$phi_coherence
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    local.get \$r5
    local.set \$r6
    local.get \$r6
    local.set \$result
    local.get \$r6
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r7
    local.get \$r7
    local.set \$result
    local.get \$r5
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r0
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r8
        local.get \$r9
    f64.ge
    f64.convert_i32_s
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$r4
    local.set \$r11
    local.get \$r11
    local.set \$result
    f64.const 24
    local.set \$r12
    local.get \$r12
    local.set \$result
    local.get \$r11
        local.get \$r12
    f64.ge
    f64.convert_i32_s
    local.set \$r13
    local.get \$r13
    local.set \$result
    local.get \$r13
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 8
      )
      (else
        ;; -> block 9
      )
    )
    ;; Block 8
    ;; Block 9
    ;; Block 10
    local.get \$result
  )
)
`,

  "healing": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 0
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    f64.const 0
    local.set \$r2
    local.get \$r2
    local.set \$result
    nop ;; StoreVar \$r2
    f64.const 0
    local.set \$r3
    local.get \$r3
    local.set \$result
    nop ;; StoreVar \$r3
    f64.const 0
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    ;; intention "System_Harmonization" (name len fallback)
    i32.const 20
    call \$phi_intention_push
    ;; Block 1
    ;; Block 2
    i32.const 3
    call \$phi_sensor
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    i32.const 4
    call \$phi_sensor
    local.set \$r6
    local.get \$r6
    local.set \$result
    nop ;; StoreVar \$r6
    i32.const 5
    call \$phi_sensor
    local.set \$r7
    local.get \$r7
    local.set \$result
    nop ;; StoreVar \$r7
    local.get \$r5
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r8
    call \$phi_resonate
    local.get \$r6
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r9
    call \$phi_resonate
    local.get \$r7
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    call \$phi_resonate
    call \$phi_coherence
    local.set \$r11
    local.get \$r11
    local.set \$result
    nop ;; StoreVar \$r11
    i32.const -1
    call \$phi_witness
    local.set \$r12
    local.get \$r12
    local.set \$result
    local.get \$r15
    local.set \$r13
    local.get \$r13
    local.set \$result
    f64.const 1
    local.set \$r14
    local.get \$r14
    local.set \$result
    local.get \$r13
        local.get \$r14
    f64.add
    local.set \$r15
    local.get \$r15
    local.set \$result
    nop ;; StoreVar \$r15
    local.get \$r11
    local.set \$r16
    local.get \$r16
    local.set \$result
    f64.const 0.618
    local.set \$r17
    local.get \$r17
    local.set \$result
    local.get \$r16
        local.get \$r17
    f64.ge
    f64.convert_i32_s
    local.set \$r18
    local.get \$r18
    local.set \$result
    local.get \$r18
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    call \$phi_intention_pop
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$r15
    local.set \$r19
    local.get \$r19
    local.set \$result
    f64.const 100
    local.set \$r20
    local.get \$r20
    local.set \$result
    local.get \$r19
        local.get \$r20
    f64.ge
    f64.convert_i32_s
    local.set \$r21
    local.get \$r21
    local.set \$result
    local.get \$r21
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 8
      )
      (else
        ;; -> block 9
      )
    )
    ;; Block 8
    ;; Block 9
    ;; Block 10
    local.get \$result
  )
)
`,

};
