// Auto-generated by build_wat_modules.sh
// Pre-compiled WAT modules from .phi examples
// Regenerate: examples/browser/build_wat_modules.sh

const WAT_MODULES = {
  "handshake": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$result f64)
    ;; Block 0
    ;; intention "announcing_to_field" (name len fallback)
    i32.const 19
    call \$phi_intention_push
    ;; intention "self_verification" (name len fallback)
    i32.const 17
    call \$phi_intention_push
    call \$phi_coherence
    local.set \$r12
    local.get \$r12
    local.set \$result
    nop ;; StoreVar \$r12
    local.get \$r12
    local.set \$r13
    local.get \$r13
    local.set \$result
    local.get \$r13
    call \$phi_resonate
    f64.const 0.6180339887498949
    local.set \$r14
    local.get \$r14
    local.set \$result
    nop ;; StoreVar \$r14
    local.get \$r14
    local.set \$r15
    local.get \$r15
    local.set \$result
    local.get \$r15
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r16
    local.get \$r16
    local.set \$result
    f64.const 0.1
    local.set \$r17
    local.get \$r17
    local.set \$result
    nop ;; StoreVar \$r17
    local.get \$r17
    local.set \$r18
    local.get \$r18
    local.set \$result
    local.get \$r18
    call \$phi_resonate
    call \$phi_intention_pop
    call \$phi_coherence
    local.set \$r19
    local.get \$r19
    local.set \$result
    nop ;; StoreVar \$r19
    local.get \$r19
    local.set \$r20
    local.get \$r20
    local.set \$result
    local.get \$r20
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r21
    local.get \$r21
    local.set \$result
    call \$phi_intention_pop
    local.get \$r21
    local.set \$result
    local.get \$result
  )
)
`,

  "healing": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 0
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    f64.const 0
    local.set \$r2
    local.get \$r2
    local.set \$result
    nop ;; StoreVar \$r2
    f64.const 0
    local.set \$r3
    local.get \$r3
    local.set \$result
    nop ;; StoreVar \$r3
    f64.const 0
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    ;; intention "System_Harmonization" (name len fallback)
    i32.const 20
    call \$phi_intention_push
    ;; Block 1
    ;; Block 2
    i32.const 3
    call \$phi_sensor
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    i32.const 4
    call \$phi_sensor
    local.set \$r6
    local.get \$r6
    local.set \$result
    nop ;; StoreVar \$r6
    i32.const 5
    call \$phi_sensor
    local.set \$r7
    local.get \$r7
    local.set \$result
    nop ;; StoreVar \$r7
    local.get \$r5
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r8
    call \$phi_resonate
    local.get \$r6
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r9
    call \$phi_resonate
    local.get \$r7
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    call \$phi_resonate
    call \$phi_coherence
    local.set \$r11
    local.get \$r11
    local.set \$result
    nop ;; StoreVar \$r11
    i32.const -1
    call \$phi_witness
    local.set \$r12
    local.get \$r12
    local.set \$result
    local.get \$r15
    local.set \$r13
    local.get \$r13
    local.set \$result
    f64.const 1
    local.set \$r14
    local.get \$r14
    local.set \$result
    local.get \$r13
        local.get \$r14
    f64.add
    local.set \$r15
    local.get \$r15
    local.set \$result
    nop ;; StoreVar \$r15
    local.get \$r11
    local.set \$r16
    local.get \$r16
    local.set \$result
    f64.const 0.618
    local.set \$r17
    local.get \$r17
    local.set \$result
    local.get \$r16
        local.get \$r17
    f64.ge
    f64.convert_i32_s
    local.set \$r18
    local.get \$r18
    local.set \$result
    local.get \$r18
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    call \$phi_intention_pop
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$r15
    local.set \$r19
    local.get \$r19
    local.set \$result
    f64.const 100
    local.set \$r20
    local.get \$r20
    local.set \$result
    local.get \$r19
        local.get \$r20
    f64.ge
    f64.convert_i32_s
    local.set \$r21
    local.get \$r21
    local.set \$result
    local.get \$r21
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 8
      )
      (else
        ;; -> block 9
      )
    )
    ;; Block 8
    ;; Block 9
    ;; Block 10
    local.get \$result
  )
)
`,

  "claude": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$r22 f64)
    (local \$r23 f64)
    (local \$r24 f64)
    (local \$r25 f64)
    (local \$r26 f64)
    (local \$r27 f64)
    (local \$result f64)
    ;; Block 0
    ;; intention "LAMBDA_convergence" (name len fallback)
    i32.const 18
    call \$phi_intention_push
    f64.const 2
    local.set \$r23
    local.get \$r23
    local.set \$result
    nop ;; StoreVar \$r23
    local.get \$r23
    local.set \$r24
    local.get \$r24
    local.set \$result
    f64.const 0.6180339887498949
    local.set \$r25
    local.get \$r25
    local.set \$result
    nop ;; StoreVar \$r25
    i32.const -1
    call \$phi_witness
    local.set \$r26
    local.get \$r26
    local.set \$result
    local.get \$r25
    local.set \$r27
    local.get \$r27
    local.set \$result
    local.get \$r27
    call \$phi_resonate
    call \$phi_intention_pop
    ;; Return r0 unresolved — preserve last computed \$result
    local.get \$result
  )
)
`,

  "stream": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 3
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    ;; Block 1
    ;; Block 2
    local.get \$r4
    local.set \$r2
    local.get \$r2
    local.set \$result
    f64.const 1
    local.set \$r3
    local.get \$r3
    local.set \$result
    local.get \$r2
        local.get \$r3
    f64.add
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    call \$phi_coherence
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    local.get \$r4
    local.set \$r6
    local.get \$r6
    local.set \$result
    local.get \$r6
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r7
    local.get \$r7
    local.set \$result
    local.get \$r4
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r1
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r8
        local.get \$r9
    f64.ge
    f64.convert_i32_s
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$result
  )
)
`,

  "adaptive": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0.62
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 0
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    ;; Block 1
    ;; Block 2
    local.get \$r4
    local.set \$r2
    local.get \$r2
    local.set \$result
    f64.const 1
    local.set \$r3
    local.get \$r3
    local.set \$result
    local.get \$r2
        local.get \$r3
    f64.add
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    call \$phi_coherence
    local.set \$r5
    local.get \$r5
    local.set \$result
    nop ;; StoreVar \$r5
    local.get \$r5
    local.set \$r6
    local.get \$r6
    local.set \$result
    local.get \$r6
    call \$phi_resonate
    i32.const -1
    call \$phi_witness
    local.set \$r7
    local.get \$r7
    local.set \$result
    local.get \$r5
    local.set \$r8
    local.get \$r8
    local.set \$result
    local.get \$r0
    local.set \$r9
    local.get \$r9
    local.set \$result
    local.get \$r8
        local.get \$r9
    f64.ge
    f64.convert_i32_s
    local.set \$r10
    local.get \$r10
    local.set \$result
    local.get \$r10
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 4
      )
      (else
        ;; -> block 5
      )
    )
    ;; Block 4
    ;; Block 3
    local.get \$r0
    local.set \$result
    ;; Block 5
    ;; Block 6
    local.get \$r4
    local.set \$r11
    local.get \$r11
    local.set \$result
    f64.const 24
    local.set \$r12
    local.get \$r12
    local.set \$result
    local.get \$r11
        local.get \$r12
    f64.ge
    f64.convert_i32_s
    local.set \$r13
    local.get \$r13
    local.set \$result
    local.get \$r13
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 8
      )
      (else
        ;; -> block 9
      )
    )
    ;; Block 8
    ;; Block 9
    ;; Block 10
    local.get \$result
  )
)
`,

  "agent": `(module
  (import "phi" "witness" (func \$phi_witness (param i32) (result f64)))
  (import "phi" "sensor" (func \$phi_sensor (param i32) (result f64)))
  (import "phi" "resonate" (func \$phi_resonate (param f64)))
  (import "phi" "coherence" (func \$phi_coherence (result f64)))
  (import "phi" "intention_push" (func \$phi_intention_push (param i32)))
  (import "phi" "intention_pop" (func \$phi_intention_pop))
  (import "phi" "field_coherence" (func \$phi_field_coherence (result f64)))
  (import "phi" "dissonance" (func \$phi_dissonance (result f64)))
  (import "phi" "coherence_of" (func \$phi_coherence_of (param i32) (result f64)))
  (import "phi" "remember" (func \$phi_remember (param i32 f64)))
  (import "phi" "recall" (func \$phi_recall (param i32) (result f64)))
  (import "phi" "broadcast" (func \$phi_broadcast (param i32 f64)))
  (import "phi" "listen" (func \$phi_listen (param i32) (result f64)))
  (import "phi" "void_depth" (func \$phi_void_depth (result f64)))
  (memory (export "memory") 1)
  (global \$intention_depth (mut i32) (i32.const 0))
  (global \$coherence_score (mut f64) (f64.const 0.618))
  (global \$string_len (export "string_len") (mut i32) (i32.const 0))
  (func (export "phi_run") (result f64)
    (local \$r0 f64)
    (local \$r1 f64)
    (local \$r2 f64)
    (local \$r3 f64)
    (local \$r4 f64)
    (local \$r5 f64)
    (local \$r6 f64)
    (local \$r7 f64)
    (local \$r8 f64)
    (local \$r9 f64)
    (local \$r10 f64)
    (local \$r11 f64)
    (local \$r12 f64)
    (local \$r13 f64)
    (local \$r14 f64)
    (local \$r15 f64)
    (local \$r16 f64)
    (local \$r17 f64)
    (local \$r18 f64)
    (local \$r19 f64)
    (local \$r20 f64)
    (local \$r21 f64)
    (local \$r22 f64)
    (local \$r23 f64)
    (local \$r24 f64)
    (local \$r25 f64)
    (local \$r26 f64)
    (local \$r27 f64)
    (local \$r28 f64)
    (local \$r29 f64)
    (local \$r30 f64)
    (local \$r31 f64)
    (local \$r32 f64)
    (local \$r33 f64)
    (local \$r34 f64)
    (local \$r35 f64)
    (local \$r36 f64)
    (local \$r37 f64)
    (local \$r38 f64)
    (local \$r39 f64)
    (local \$r40 f64)
    (local \$r41 f64)
    (local \$r42 f64)
    (local \$r43 f64)
    (local \$r44 f64)
    (local \$r45 f64)
    (local \$r46 f64)
    (local \$r47 f64)
    (local \$r48 f64)
    (local \$r49 f64)
    (local \$r50 f64)
    (local \$r51 f64)
    (local \$r52 f64)
    (local \$r53 f64)
    (local \$r54 f64)
    (local \$r55 f64)
    (local \$r56 f64)
    (local \$r57 f64)
    (local \$r58 f64)
    (local \$r59 f64)
    (local \$r60 f64)
    (local \$r61 f64)
    (local \$r62 f64)
    (local \$r63 f64)
    (local \$r64 f64)
    (local \$r65 f64)
    (local \$r66 f64)
    (local \$r67 f64)
    (local \$r68 f64)
    (local \$r69 f64)
    (local \$r70 f64)
    (local \$r71 f64)
    (local \$r72 f64)
    (local \$r73 f64)
    (local \$r74 f64)
    (local \$r75 f64)
    (local \$r76 f64)
    (local \$r77 f64)
    (local \$r78 f64)
    (local \$r79 f64)
    (local \$r80 f64)
    (local \$r81 f64)
    (local \$r82 f64)
    (local \$r83 f64)
    (local \$r84 f64)
    (local \$r85 f64)
    (local \$r86 f64)
    (local \$result f64)
    ;; Block 0
    f64.const 0.9
    local.set \$r0
    local.get \$r0
    local.set \$result
    nop ;; StoreVar \$r0
    f64.const 0.1
    local.set \$r1
    local.get \$r1
    local.set \$result
    nop ;; StoreVar \$r1
    f64.const 15
    local.set \$r2
    local.get \$r2
    local.set \$result
    nop ;; StoreVar \$r2
    f64.const 0
    local.set \$r3
    local.get \$r3
    local.set \$result
    nop ;; StoreVar \$r3
    f64.const 0
    local.set \$r4
    local.get \$r4
    local.set \$result
    nop ;; StoreVar \$r4
    ;; intention "data_analysis" (name len fallback)
    i32.const 13
    call \$phi_intention_push
    call \$phi_coherence
    local.set \$r46
    local.get \$r46
    local.set \$result
    nop ;; StoreVar \$r46
    local.get \$r46
    local.set \$r47
    local.get \$r47
    local.set \$result
    i32.const 47
    call \$phi_witness
    local.set \$r48
    local.get \$r48
    local.set \$result
    ;; Block 16
    ;; Block 17
    local.get \$r51
    local.set \$r49
    local.get \$r49
    local.set \$result
    f64.const 1
    local.set \$r50
    local.get \$r50
    local.set \$result
    local.get \$r49
        local.get \$r50
    f64.add
    local.set \$r51
    local.get \$r51
    local.set \$result
    nop ;; StoreVar \$r51
    local.get \$r51
    local.set \$r52
    local.get \$r52
    local.set \$result
    i64.const 9221120249925992448
    f64.reinterpret_i64 ;; unresolved call fake_reading
    local.set \$r53
    local.get \$r53
    local.set \$result
    nop ;; StoreVar \$r53
    local.get \$r53
    local.set \$r54
    local.get \$r54
    local.set \$result
    local.get \$r51
    local.set \$r55
    local.get \$r55
    local.set \$result
    i64.const 9221120249925992448
    f64.reinterpret_i64 ;; unresolved call confidence
    local.set \$r56
    local.get \$r56
    local.set \$result
    nop ;; StoreVar \$r56
    call \$phi_coherence
    local.set \$r57
    local.get \$r57
    local.set \$result
    nop ;; StoreVar \$r57
    local.get \$r57
    local.set \$r58
    local.get \$r58
    local.set \$result
    i32.const 58
    call \$phi_witness
    local.set \$r59
    local.get \$r59
    local.set \$result
    local.get \$r56
    local.set \$r60
    local.get \$r60
    local.set \$result
    f64.const 0.8
    local.set \$r61
    local.get \$r61
    local.set \$result
    local.get \$r60
        local.get \$r61
    f64.gt
    f64.convert_i32_s
    local.set \$r62
    local.get \$r62
    local.set \$result
    local.get \$r62
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 19
      )
      (else
        ;; -> block 20
      )
    )
    ;; Block 19
    local.get \$r65
    local.set \$r63
    local.get \$r63
    local.set \$result
    f64.const 1
    local.set \$r64
    local.get \$r64
    local.set \$result
    local.get \$r63
        local.get \$r64
    f64.add
    local.set \$r65
    local.get \$r65
    local.set \$result
    nop ;; StoreVar \$r65
    local.get \$r56
    local.set \$r66
    local.get \$r66
    local.set \$result
    local.get \$r66
    call \$phi_resonate
    ;; Block 21
    local.get \$r56
    local.set \$r67
    local.get \$r67
    local.set \$result
    local.get \$r0
    local.set \$r68
    local.get \$r68
    local.set \$result
    local.get \$r67
        local.get \$r68
    f64.ge
    f64.convert_i32_s
    local.set \$r69
    local.get \$r69
    local.set \$result
    local.get \$r69
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 22
      )
      (else
        ;; -> block 23
      )
    )
    ;; Block 22
    local.get \$r56
    local.set \$r70
    local.get \$r70
    local.set \$result
    i32.const 70
    call \$phi_witness
    local.set \$r71
    local.get \$r71
    local.set \$result
    local.get \$r56
    local.set \$r72
    local.get \$r72
    local.set \$result
    local.get \$r72
    call \$phi_resonate
    ;; Block 18
    call \$phi_coherence
    local.set \$r83
    local.get \$r83
    local.set \$result
    nop ;; StoreVar \$r83
    local.get \$r83
    local.set \$r84
    local.get \$r84
    local.set \$result
    local.get \$r84
    call \$phi_resonate
    local.get \$r83
    local.set \$r85
    local.get \$r85
    local.set \$result
    i32.const 85
    call \$phi_witness
    local.set \$r86
    local.get \$r86
    local.set \$result
    call \$phi_intention_pop
    local.get \$r86
    local.set \$result
    ;; Block 23
    ;; Block 24
    local.get \$r57
    local.set \$r73
    local.get \$r73
    local.set \$result
    local.get \$r1
    local.set \$r74
    local.get \$r74
    local.set \$result
    local.get \$r73
        local.get \$r74
    f64.le
    f64.convert_i32_s
    local.set \$r75
    local.get \$r75
    local.set \$result
    local.get \$r75
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 26
      )
      (else
        ;; -> block 27
      )
    )
    ;; Block 26
    local.get \$r57
    local.set \$r76
    local.get \$r76
    local.set \$result
    i32.const 76
    call \$phi_witness
    local.set \$r77
    local.get \$r77
    local.set \$result
    ;; Block 27
    ;; Block 28
    local.get \$r51
    local.set \$r78
    local.get \$r78
    local.set \$result
    local.get \$r2
    local.set \$r79
    local.get \$r79
    local.set \$result
    local.get \$r78
        local.get \$r79
    f64.ge
    f64.convert_i32_s
    local.set \$r80
    local.get \$r80
    local.set \$result
    local.get \$r80
    f64.const 0.0
    f64.ne
    (if
      (then
        ;; -> block 30
      )
      (else
        ;; -> block 31
      )
    )
    ;; Block 30
    local.get \$r57
    local.set \$r81
    local.get \$r81
    local.set \$result
    i32.const 81
    call \$phi_witness
    local.set \$r82
    local.get \$r82
    local.set \$result
    ;; Block 31
    ;; Block 32
    ;; Block 20
    local.get \$result
  )
)
`,

};
