#!/usr/bin/env python3.12
"""
Submit an 8-qubit GHZ circuit to IBM Quantum hardware.
Generates the QASM from PhiFlow, transpiles for the target backend,
and submits. Prints the job ID for the Rust CLI to poll.
"""

import sys
import json
from pathlib import Path
sys.path.insert(0, "/mnt/d/Pi/routing")
from cascade_keys import get_key


# QASM generated by PhiFlow -- this is a true 8-qubit GHZ state:
# Q0: ry(pi/2) -> superposition
# CX chain: Q0->Q1->...->Q7
# Result: (|00000000> + |11111111>) / sqrt(2)
GHZ_8QUBIT_QASM = """OPENQASM 3.0;
include "stdgates.inc";

qubit[8] q;
bit[8] c;

    ry(0.5 * pi) q[0];
    cx q[0], q[1];
    cx q[1], q[2];
    cx q[2], q[3];
    cx q[3], q[4];
    cx q[4], q[5];
    cx q[5], q[6];
    cx q[6], q[7];

    c[0] = measure q[0];
    c[1] = measure q[1];
    c[2] = measure q[2];
    c[3] = measure q[3];
    c[4] = measure q[4];
    c[5] = measure q[5];
    c[6] = measure q[6];
    c[7] = measure q[7];
"""


def get_token() -> str:
    """Read IBM_QUANTUM_TOKEN from the CASCADE vault via cascade_keys."""
    token = get_key("IBM_QUANTUM_TOKEN")
    if not token:
        raise KeyError("IBM_QUANTUM_TOKEN not found in vault")
    return token


def submit_ghz(backend_name="ibm_marrakesh", shots=4096):
    """Submit the 8-qubit GHZ circuit to IBM Quantum."""
    from qiskit_ibm_runtime import QiskitRuntimeService
    from qiskit import QuantumCircuit
    from qiskit.qasm3 import loads as qasm3_loads

    token = get_token()
    service = QiskitRuntimeService(channel='ibm_quantum_platform', token=token)

    # Parse the QASM
    circuit = qasm3_loads(GHZ_8QUBIT_QASM)
    print(f"Circuit: {circuit.num_qubits} qubits, {circuit.num_clbits} classical bits")
    print(f"Circuit depth: {circuit.depth()}")
    print(f"Gate count: {circuit.count_ops()}")

    # Transpile for the backend's native gate set
    from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
    backend = service.backend(backend_name)
    print(f"\nBackend: {backend.name}")
    print(f"  Qubits: {backend.num_qubits}")

    pm = generate_preset_pass_manager(optimization_level=1, backend=backend)
    isa_circuit = pm.run(circuit)
    print(f"Transpiled circuit depth: {isa_circuit.depth()}")
    print(f"Transpiled gate count: {isa_circuit.count_ops()}")

    # Submit using SamplerV2
    from qiskit_ibm_runtime import SamplerV2
    sampler = SamplerV2(backend)
    job = sampler.run([(isa_circuit,)], shots=shots)

    print(f"\nJob submitted!")
    print(f"  Job ID: {job.job_id()}")
    print(f"  Shots: {shots}")
    print(f"  Circuit: 8-qubit GHZ state")

    # Save job info
    job_info = {
        "job_id": job.job_id(),
        "backend": backend_name,
        "circuit": "8-qubit GHZ",
        "shots": shots,
        "qasm": GHZ_8QUBIT_QASM,
    }
    info_path = f"/tmp/ibm_job_{job.job_id()}_info.json"
    with open(info_path, 'w') as f:
        json.dump(job_info, f, indent=2)
    print(f"  Job info saved to: {info_path}")

    return job.job_id()


if __name__ == '__main__':
    backend = sys.argv[1] if len(sys.argv) > 1 else "ibm_marrakesh"
    shots = int(sys.argv[2]) if len(sys.argv) > 2 else 4096

    print("=" * 60)
    print("  8-Qubit GHZ State — IBM Quantum Submission")
    print("=" * 60)
    print(f"  Backend: {backend}")
    print(f"  Shots: {shots}")
    print(f"  Circuit: (|00000000> + |11111111>) / sqrt(2)")
    print(f"  Question: How does entanglement coherence scale")
    print(f"            with qubit count on Heron hardware?")
    print(f"  Baseline: 3-qubit GHZ = 0.3496 on ibm_marrakesh")
    print("=" * 60)

    job_id = submit_ghz(backend, shots)
    print(f"\n  To poll: python3.12 scripts/poll_ibm_real.py {job_id}")
    print("=" * 60)